// Auto-generated by gen_gelu4_coeffs.py -- do not edit by hand.
// erf-GELU bump q(s)=G(-s) on u=(s-shift)*scale, u in [-1,1].
// GELU(x) = relu(x) + q(|x|); q = 0 beyond the last break.
#define GELU4_NPIECE 3
#define GELU4_DEG 4
static const float GELU4_BREAK[GELU4_NPIECE] = {1.000000f, 2.000000f, 4.000000f};
static const float GELU4_SHIFT[GELU4_NPIECE] = {0.500000f, 1.500000f, 3.000000f};
static const float GELU4_SCALE[GELU4_NPIECE] = {2.000000f, 2.000000f, 1.000000f};
static const float GELU4_COEF[GELU4_NPIECE][GELU4_DEG+1] = {
  {-0.0020446777f, -0.013000488f, 0.077148438f, -0.06640625f, -0.15429688f},
  {0.0021514893f, -0.0071716309f, -0.0040283203f, 0.063964844f, -0.10009766f},
  {-0.0029296875f, 0.010681152f, -0.015869141f, 0.012023926f, -0.0040283203f},
};
