#!/usr/bin/env python3
"""Coefficients for gelu_row4.cc -- the cheap form of the erf-GELU bump.

g3 fits q(s)=G(-s) in the monomial basis on raw s over five pieces of degree 4,
and pays for it twice: 20 Horner steps, and every step carrying the fp32 state as
a bf16 hi/lo pair because plain bf16 coefficients were catastrophic there
(downstream 0.94).

Both costs are conditioning, not bf16. Mapping each piece onto u in [-1, 1]
keeps the Horner state O(1) and the coefficients O(0.1), and then bf16 state AND
bf16 coefficients both hold (measured, measured through the real fc2):

    g3   5 pieces x d4, raw s,  hi/lo state, hi/lo coeffs   downstream 0.00663
    g4   3 pieces x d4, u,      bf16  state, bf16  coeffs   downstream 0.00681

12 steps instead of 20, and each step is a conversion, a multiply and a MAC
instead of two conversions, a subtract, six multiplies and three adds.

Same invariant as gen_gelu_coeffs.py: this file is the ONLY source of the
numbers, and both the kernel and the numpy validator read what it emits, so the
two cannot silently diverge.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from repo_paths import ROOT, KERNELS
import numpy as np
from ml_dtypes import bfloat16

import npu_whisper_encoder as E

ACTS = str(ROOT / "fc1_acts.npy")
HDR = str(KERNELS / "gelu_poly4_coeffs.h")
NPY = str(ROOT / "gelu_poly4_coeffs.npz")

BREAKS = [0.0, 1.0, 2.0, 4.0]
DEG = 4


def bf(a):
    return np.asarray(a, np.float32).astype(bfloat16).astype(np.float32)


def q_true(s):
    s = np.asarray(s, np.float64)
    return 0.5 * (-s) * (1.0 + E._erf(-s / np.sqrt(2.0)))


if not Path(ACTS).exists():
    sys.exit(f"{ACTS} not found. Produce it with:\n"
             f"  python3 bench/run_raw_encoder.py --host-mlp --iters 1 "
             f"--dump-fc1-acts {ACTS}")
x = np.load(ACTS).reshape(-1).astype(np.float32)
absx = np.abs(x)
xs = absx[np.random.default_rng(0).choice(absx.size, 400000, replace=False)]

# shift/scale are multiplied into the kernel's bf16 vectors, so they are rounded
# to bf16 FIRST and the fit is done against the rounded values -- otherwise the
# fit optimises for a variable the kernel never actually forms.
shifts, scales, coeffs = [], [], []
for a, b in zip(BREAKS[:-1], BREAKS[1:]):
    sh = bf((a + b) / 2.0)
    sc = bf(2.0 / (b - a))
    sel = xs[(xs >= a) & (xs < b)]
    if sel.size < 200:
        sel = np.linspace(a, b, 400)
    u = bf((sel - sh) * sc)
    c = np.linalg.lstsq(np.vander(u, DEG + 1), q_true(sel), rcond=None)[0]
    shifts.append(float(sh))
    scales.append(float(sc))
    coeffs.append(bf(c))                        # highest degree first, bf16-exact

coeffs = np.stack(coeffs).astype(np.float32)
np.savez(NPY, breaks=np.array(BREAKS), shifts=np.array(shifts),
         scales=np.array(scales), coeffs=coeffs)

with open(HDR, "w") as f:
    f.write("// Auto-generated by gen_gelu4_coeffs.py -- do not edit by hand.\n")
    f.write("// erf-GELU bump q(s)=G(-s) on u=(s-shift)*scale, u in [-1,1].\n")
    f.write("// GELU(x) = relu(x) + q(|x|); q = 0 beyond the last break.\n")
    f.write(f"#define GELU4_NPIECE {len(coeffs)}\n")
    f.write(f"#define GELU4_DEG {DEG}\n")
    f.write("static const float GELU4_BREAK[GELU4_NPIECE] = {"
            + ", ".join(f"{v:.6f}f" for v in BREAKS[1:]) + "};\n")
    f.write("static const float GELU4_SHIFT[GELU4_NPIECE] = {"
            + ", ".join(f"{v:.6f}f" for v in shifts) + "};\n")
    f.write("static const float GELU4_SCALE[GELU4_NPIECE] = {"
            + ", ".join(f"{v:.6f}f" for v in scales) + "};\n")
    f.write("static const float GELU4_COEF[GELU4_NPIECE][GELU4_DEG+1] = {\n")
    for c in coeffs:
        f.write("  {" + ", ".join(f"{float(v):.8g}f" for v in c) + "},\n")
    f.write("};\n")

print("wrote", HDR, "and", NPY)
for (a, b), sh, sc, c in zip(zip(BREAKS[:-1], BREAKS[1:]), shifts, scales,
                             coeffs):
    print(f"  s in [{a:.2f},{b:.2f}): u=(s-{sh})*{sc}  "
          f"{[float(v) for v in c]}")
