#!/usr/bin/env python3
"""Fit the piecewise erf-GELU bump q(s)=G(-s) and emit ONE source of truth for
both the AIE kernel and the numpy validator: gelu_poly_coeffs.h.

Design: G(x) = relu(x) + q(|x|). q fit on real fc1
activations (absolute-error = output impact), degree 4, five pieces, coeffs
rounded to bf16 and re-fit on the bf16 grid. Zero beyond s=4.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from repo_paths import ROOT, KERNELS
import numpy as np
from ml_dtypes import bfloat16
import npu_whisper_encoder as E

ACTS = str(ROOT / "fc1_acts.npy")
HDR = str(KERNELS / "gelu_poly_coeffs.h")
NPY = str(ROOT / "gelu_poly_coeffs.npz")

BREAKS = [0.0, 0.5, 1.0, 1.75, 2.75, 4.0]
DEG = 4


def bf(a):
    return np.asarray(a, np.float32).astype(bfloat16).astype(np.float32)


def q_true(s):
    s = np.asarray(s, np.float64)
    return 0.5 * (-s) * (1.0 + E._erf(-s / np.sqrt(2.0)))


if not Path(ACTS).exists():
    sys.exit(f"{ACTS} not found. Produce it with:\n"
             f"  python3 bench/run_raw_encoder.py --host-mlp --iters 1 "
             f"--dump-fc1-acts {ACTS}")
x = np.load(ACTS).reshape(-1).astype(np.float32)
absx = np.abs(x)
xs = absx[np.random.default_rng(0).choice(absx.size, 400000, replace=False)]

pieces = []
for a, b in zip(BREAKS[:-1], BREAKS[1:]):
    sel = xs[(xs >= a) & (xs < b)]
    if sel.size < 50:
        sel = np.linspace(a, b, 200)
    y = q_true(sel)
    # fp32 fit; the kernel carries each coefficient as a bf16 hi/lo pair, so the
    # bf16 grid refit is unnecessary -- and bf16-rounding the coeffs outright is
    # catastrophic downstream (0.94 vs 0.006 for hi/lo, measured).
    c = np.linalg.lstsq(np.vander(sel, DEG + 1), y, rcond=None)[0]
    pieces.append(np.asarray(c, np.float32))      # highest degree first

coeffs = np.stack(pieces).astype(np.float32)       # (5, DEG+1) fp32
chi = bf(coeffs)                                   # bf16 hi part
clo = bf(coeffs - chi)                             # bf16 lo part
np.savez(NPY, breaks=np.array(BREAKS), coeffs=coeffs)

with open(HDR, "w") as f:
    f.write("// Auto-generated by gen_gelu_coeffs.py -- do not edit by hand.\n")
    f.write("// Piecewise minimax erf-GELU bump q(s)=G(-s); GELU=relu(x)+q(|x|).\n")
    f.write(f"#define GELU_NPIECE {len(pieces)}\n")
    f.write(f"#define GELU_DEG {DEG}\n")
    # breakpoints 1..NPIECE-1 as the upper edge of each inner piece; the last
    # region (s >= last break) returns 0
    ub = BREAKS[1:]
    f.write("static const float GELU_BREAK[GELU_NPIECE] = {")
    f.write(", ".join(f"{v:.6f}f" for v in ub) + "};\n")
    # coeffs[piece][k], k=0 highest degree
    for nm, arr in (("GELU_COEF_HI", chi), ("GELU_COEF_LO", clo)):
        f.write(f"static const float {nm}[GELU_NPIECE][GELU_DEG+1] = {{\n")
        for c in arr:
            f.write("  {" + ", ".join(f"{float(v):.8g}f" for v in c) + "},\n")
        f.write("};\n")

print("wrote", HDR, "and", NPY)
print(f"breaks {BREAKS}, degree {DEG}, {len(pieces)} pieces")
for (a, b), c in zip(zip(BREAKS[:-1], BREAKS[1:]), coeffs):
    print(f"  s in [{a:.2f},{b:.2f}): {[float(v) for v in c]}")
